travis:
  secure:
    BINSTAR_TOKEN: JumObx3sUWEdrQ7Mas5dyx5I+N8zx8QUlaqIDcIfyRsZrehYhVaLD7aZqFHOaVf9kdSIDEYSUspnJXjp5mloY8e9yqjAugFh9xO9PaNIpQKHREJjnzyDTtojAiZK/mBSlRxsC7aYIXkxP2G37kvaCmPBjkSz/jHCGyPhDX8dezj+xwo6X7htW2Qn4hTuVHvViJ+yRujbhjf4g6eRtk/iqiJB7JCdOzYVU/Nc6HTJP2rWXwzf1W3gPWZGgRBTs0USbvJuE9IReoTBhOB9laSne/YD+VsDJcsfzUC6Dajf4OBv0RiKI+DBEj5VPqPvma+yTJiaLBSa2o1+7o46RGR+uRlhBZGMTBugHd0EWjr4ynys8P72paOLOdrdXvutrDri89picCTUa1AORM4Li4dF+J44kdI8AWG/zx/7H2b6ZB9FNka0QjGvsJCXajo5Ru0qmFJkewZK6HgVBdsktLb3D4En3e5rOhm8i9kWLiPMviKfDOsawDK05+zrlLABJz8WSZVAmf2WHB0fpJ5pqn7KdNuQ9HpJN3injiWouLR4skRo0SyDJDIi8ci7oPGcEk9SIu+bkObagxR2FknEybSIKzCXOXvrt9qstL9xrWHm+B7HBscvr7knhRrmmDrx9OU4/e0BNhxSde/cgJdDI1qShjkiJPf5GkqBeRzu7LOs/9U=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
