travis:
  secure:
    BINSTAR_TOKEN: RVWNOMo2ms8pVkBaOKQHLWoFalMprflgM665V8wXTvI8Kyp6Qq/lNrV/uO1KsvhFNszEykk53WgSJxEg5CJ5dz39Zz53qGOaGbMK1nE33/LCW+STfsdCC7HHovFZ3QEtOkvQwuZPPwPVRZ6gFEX01na9BmUT9Vyw+5pt9o4LeHdIJRAc8xOTifYPaV3PoLTkPXXmKeDiV+iXLEd3YTfr7eIvizGjGHpCT2bqgSh9fIsJNQtPF4GTeD7M5uAUVFEMe/b9FtjJVk0A7wut4KOcLNAK2ZcSya3tizlXHLODt6qaeydxTcMUlf3AlnW1Qvg4MSgO8T20oAOrhnPUB3FdLgPnOsIgvGd51szyLbUay2bnSFY8NOLoICoz9wG1SzzdWM24L2TFsEF0gi8W4iDHZkolJz2MyIeSXwvSWXGhwqDGVK7kqoZVFqqwBOjYJjDxaFFM93/E1V8voiUSsELNhTIJoB7wcAo7ala/1qQ6xR0dWDKvKIQBkHxRfRTgwtRIhxHf4xtLPVwKCbRk1KAY4FbFcNaQDp0uUrXGSosqWCbH3BAcKSszNtq+r4whFRJhV5dNrc/7R5303C0t9hK6rSSq6Q/+C56ip4jTNauNrwOqn4OoRpJBUR2laBNeAG6S+oETWfuTokQf98Krd47iFHfoajf53wVuG71m87g7/kE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
