travis:
  secure:
    BINSTAR_TOKEN: Z9KGUJl8dUETqLaudOC8Qb8mX88jt16oSk2MTspZD3WZq53/XG0RU8hVJ/kCZOES5AgzNoyTla+MTF1hbvRl/2tmvWTI6DVNkgdpd8wA9HfKW0uUMSfD5a+Jf4D67GsjFExJgfi/ykRrNIwc7JoVkDBBarOHl7/bSAK8OPK2hiFO/1ycbqAkG5X3dD7iW9/ERc6ROSMzmKFDGcvGbKajWAGZyZs03j6mC+enDrC/kiiiKBEcSTJr8evhJjid4NuWdlZ0/Aaf9EolRS/8KaPFRaOsMphPbPZ7An9I8bB/9UbSQ/sPOyc23n8Vg2LgszkBFtWueKf9dSLUq6HSNRmNQWCzpNDkcbmgtdjJTb3sWvk5/ssNHrBGuenit90h+0AEIlPdKC+kKVNv6plNu64tOOjqbv6wcjyhHBSfhDzrmYfNSZBUd1R99weS7ANIauDPOcFc2zpxxC9hALA41T6IYe3d7Xr5CBvKbGHINHr3jQ5jKDtVmZ5A6bwqXrKAu4+5rbdkSZUd6HFWAKoNEjZByUUyq6WyExpIL7uRwryFoWH3fd9Ayvk3/9xkbuewXtQ7yrlbzBqDlYoMf2O9Do7P78PJsbWOmM4TGOdzV+tI883tniO22tpjfTd+RpnSsJkktkTqJOY5tq3i4mwMA5bQ/V5HLXYvZCeotnh6L7E/kYs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
